### PR TITLE
Added HLS support for Apple and non Apple platforms

### PR DESCRIPTION
**Pull request by brapifra**
Changes proposed in this pull request:
- Add HLS native player for apple devices (iOS and macOS)
- Keep HLS.js player for non iOS devices

### CODE REVIEW

**Comment by brapifra** [comment]
@rubenrua Review the pull request

**Comment by brapifra** [comment]
I've made the commit and pull request in the master branch, my bad. Sorry.

**Comment by miesgre** [comment]
@brapifra This pull request have conflicts, please resolve them.

With this PR, iOS devices can play HLS, but I  think muti-quality HLS will not be supported in iOS. Did you tested multi-quality HLS on iOS?

**Comment by miesgre** [comment]
I'm closing this PR because @ferserc1 fixed it in commit 89545e60cc9d83d490f3259c004b2c54d1032362

**Comment by brapifra** [comment]
I've overwritten the feature branch with the last commit 89545e6 and I've added iPad support and fixed the repository_test

**Comment by miesgre** [comment]
I can not reopen this PS as your branch has forced-pushed, so I created a new PR (#270) with your changes.

**Pull request closed without merging**
