### PR TITLE
Refactored image/time overlay, use absolute instead of fixed position

### PR DESCRIPTION
**Pull request by jjeising**
Use absolute instead of fixed position. This enables using the player embedded with other elements on the page. Also started to cleanup `movePassive`.

### CODE REVIEW

**Comment by miesgre** [comment]
@ferserc1 Please take a look to this

**Comment by jjeising** [comment]
There are one or two small issues I still have to change before this might get merged. It should use `paella.utils.timeParse.secondsToTime` (one of three methods I've found that does this conversion) for example.

**Comment by miesgre** [comment]
Ok, so, when you have done those changes, inform us and @ferserc1 will look this PR.

Thanks

**Comment by jjeising** [comment]
This is probably outdated and currently there will be no further development on my side.

**Pull request closed without merging**
